# Generated by Django 4.1.1 on 2022-09-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordsaver',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
